# Generated by Django 5.0.6 on 2024-05-27 08:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Confederation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("title_ru", models.CharField(max_length=256, null=True)),
                ("title_uz", models.CharField(max_length=256, null=True)),
                ("title_en", models.CharField(max_length=256, null=True)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "content_ru",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "content_uz",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "content_en",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
            ],
            options={
                "verbose_name": "Confederation",
                "verbose_name_plural": "Confederation",
            },
        ),
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("title_ru", models.CharField(max_length=256, null=True)),
                ("title_uz", models.CharField(max_length=256, null=True)),
                ("title_en", models.CharField(max_length=256, null=True)),
                (
                    "pdf",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "pdf_ru",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "pdf_uz",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "pdf_en",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                ("file_name", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "file_name_ru",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "file_name_uz",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "file_name_en",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
            ],
            options={
                "verbose_name": "Documents",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.CreateModel(
            name="Guides",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("title_ru", models.CharField(max_length=256, null=True)),
                ("title_uz", models.CharField(max_length=256, null=True)),
                ("title_en", models.CharField(max_length=256, null=True)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "content_ru",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "content_uz",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "content_en",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
            ],
            options={
                "verbose_name": "Guides",
                "verbose_name_plural": "Guides",
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("title_ru", models.CharField(max_length=256, null=True)),
                ("title_uz", models.CharField(max_length=256, null=True)),
                ("title_en", models.CharField(max_length=256, null=True)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "content_ru",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "content_uz",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "content_en",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
            ],
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Membership",
            },
        ),
        migrations.CreateModel(
            name="Regulations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("title_ru", models.CharField(max_length=256, null=True)),
                ("title_uz", models.CharField(max_length=256, null=True)),
                ("title_en", models.CharField(max_length=256, null=True)),
                (
                    "pdf",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "pdf_ru",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "pdf_uz",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "pdf_en",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                ("file_name", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "file_name_ru",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "file_name_uz",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "file_name_en",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
            ],
            options={
                "verbose_name": "Regulations",
                "verbose_name_plural": "Regulations",
            },
        ),
        migrations.CreateModel(
            name="Symbols",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("title_ru", models.CharField(max_length=256, null=True)),
                ("title_uz", models.CharField(max_length=256, null=True)),
                ("title_en", models.CharField(max_length=256, null=True)),
            ],
            options={
                "verbose_name": "Symbols",
                "verbose_name_plural": "Symbols",
            },
        ),
    ]
