# Generated by Django 5.0.6 on 2024-05-31 03:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="carousel/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompetitionDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                ("title_ru", models.CharField(blank=True, max_length=256, null=True)),
                ("title_uz", models.CharField(blank=True, max_length=256, null=True)),
                ("title_en", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "document_ru",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "document_uz",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "document_en",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
            ],
            options={
                "verbose_name": "Competition Documents",
                "verbose_name_plural": "Competition Documents",
            },
        ),
        migrations.CreateModel(
            name="CompetitionReports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                ("title_ru", models.CharField(blank=True, max_length=256, null=True)),
                ("title_uz", models.CharField(blank=True, max_length=256, null=True)),
                ("title_en", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "document_ru",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "document_uz",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "document_en",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
            ],
            options={
                "verbose_name": "Competition Reports",
                "verbose_name_plural": "Competition Reports",
            },
        ),
        migrations.CreateModel(
            name="Confederation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("title_ru", models.CharField(max_length=256, null=True)),
                ("title_uz", models.CharField(max_length=256, null=True)),
                ("title_en", models.CharField(max_length=256, null=True)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "content_ru",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "content_uz",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "content_en",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
            ],
            options={
                "verbose_name": "Confederation",
                "verbose_name_plural": "Confederation",
            },
        ),
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("title_ru", models.CharField(max_length=256, null=True)),
                ("title_uz", models.CharField(max_length=256, null=True)),
                ("title_en", models.CharField(max_length=256, null=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("Учредительные", "Constituent"),
                            ("Устав", "Regulations"),
                            ("Положения", "Provisions"),
                            ("Протоколы", "Reports"),
                            ("Документы", "Documents"),
                        ],
                        max_length=256,
                    ),
                ),
                ("document", models.FileField(upload_to="documents/")),
                ("document_ru", models.FileField(null=True, upload_to="documents/")),
                ("document_uz", models.FileField(null=True, upload_to="documents/")),
                ("document_en", models.FileField(null=True, upload_to="documents/")),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("image", models.ImageField(upload_to="gallery/")),
                ("date", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Guides",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("title_ru", models.CharField(max_length=256, null=True)),
                ("title_uz", models.CharField(max_length=256, null=True)),
                ("title_en", models.CharField(max_length=256, null=True)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "content_ru",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "content_uz",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "content_en",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
            ],
            options={
                "verbose_name": "Guides",
                "verbose_name_plural": "Guides",
            },
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("title_ru", models.CharField(max_length=256, null=True)),
                ("title_uz", models.CharField(max_length=256, null=True)),
                ("title_en", models.CharField(max_length=256, null=True)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "content_ru",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "content_uz",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "content_en",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
            ],
            options={
                "verbose_name": "History",
                "verbose_name_plural": "History",
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("title_ru", models.CharField(max_length=256, null=True)),
                ("title_uz", models.CharField(max_length=256, null=True)),
                ("title_en", models.CharField(max_length=256, null=True)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "content_ru",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "content_uz",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "content_en",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
            ],
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Membership",
            },
        ),
        migrations.CreateModel(
            name="Regulations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                ("title_ru", models.CharField(blank=True, max_length=256, null=True)),
                ("title_uz", models.CharField(blank=True, max_length=256, null=True)),
                ("title_en", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "document_ru",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "document_uz",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "document_en",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
            ],
            options={
                "verbose_name": "Regulations",
                "verbose_name_plural": "Regulations",
            },
        ),
        migrations.CreateModel(
            name="Rules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("title_ru", models.CharField(max_length=256, null=True)),
                ("title_uz", models.CharField(max_length=256, null=True)),
                ("title_en", models.CharField(max_length=256, null=True)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "content_ru",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "content_uz",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
                (
                    "content_en",
                    ckeditor_uploader.fields.RichTextUploadingField(null=True),
                ),
            ],
            options={
                "verbose_name": "Rules",
                "verbose_name_plural": "Rules",
            },
        ),
        migrations.CreateModel(
            name="Symbols",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("title_ru", models.CharField(max_length=256, null=True)),
                ("title_uz", models.CharField(max_length=256, null=True)),
                ("title_en", models.CharField(max_length=256, null=True)),
            ],
            options={
                "verbose_name": "Symbols",
                "verbose_name_plural": "Symbols",
            },
        ),
        migrations.CreateModel(
            name="Temp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
            ],
            options={
                "verbose_name": "Documents",
                "verbose_name_plural": "Documents",
            },
        ),
    ]
