# Generated by Django 5.0.6 on 2024-05-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KurashProvisions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("title_ru", models.CharField(max_length=256, null=True)),
                ("title_uz", models.CharField(max_length=256, null=True)),
                ("title_en", models.CharField(max_length=256, null=True)),
                ("document", models.FileField(upload_to="documents/")),
                ("document_ru", models.FileField(null=True, upload_to="documents/")),
                ("document_uz", models.FileField(null=True, upload_to="documents/")),
                ("document_en", models.FileField(null=True, upload_to="documents/")),
            ],
            options={
                "verbose_name": "Положения",
                "verbose_name_plural": "Положения",
            },
        ),
        migrations.AlterModelOptions(
            name="competitiondocuments",
            options={
                "verbose_name": "Документы о соревнованиях",
                "verbose_name_plural": "Документы о соревнованиях",
            },
        ),
        migrations.AlterModelOptions(
            name="competitionreports",
            options={
                "verbose_name": "Протоколы соревнований",
                "verbose_name_plural": "Протоколы соревнований",
            },
        ),
    ]
