# Generated by Django 5.0.6 on 2024-05-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsannouncements",
            name="title_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="eventsannouncements",
            name="title_ru",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="eventsannouncements",
            name="title_uz",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
