# Generated by Django 5.0.6 on 2024-06-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_eventsannouncements_title_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="title_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="gallery",
            name="title_ru",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="gallery",
            name="title_uz",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
