# Generated by Django 5.0.6 on 2024-06-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_gallery_title_en_gallery_title_ru_gallery_title_uz"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                ("title_ru", models.CharField(max_length=256, null=True)),
                ("title_uz", models.CharField(max_length=256, null=True)),
                ("title_en", models.CharField(max_length=256, null=True)),
                ("image", models.ImageField(upload_to="gallery/")),
                ("date", models.CharField(max_length=32)),
            ],
            options={
                "verbose_name": "Галерея Фото",
                "verbose_name_plural": "Галерея Фото",
            },
        ),
    ]
