# Generated by Django 5.0.6 on 2024-05-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_history_content_en_history_content_ru_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documents",
            old_name="pdf",
            new_name="document",
        ),
        migrations.RenameField(
            model_name="documents",
            old_name="pdf_en",
            new_name="document_en",
        ),
        migrations.RenameField(
            model_name="documents",
            old_name="pdf_ru",
            new_name="document_ru",
        ),
        migrations.RenameField(
            model_name="documents",
            old_name="pdf_uz",
            new_name="document_uz",
        ),
        migrations.RenameField(
            model_name="regulations",
            old_name="pdf",
            new_name="document",
        ),
        migrations.RenameField(
            model_name="regulations",
            old_name="pdf_en",
            new_name="document_en",
        ),
        migrations.RenameField(
            model_name="regulations",
            old_name="pdf_ru",
            new_name="document_ru",
        ),
        migrations.RenameField(
            model_name="regulations",
            old_name="pdf_uz",
            new_name="document_uz",
        ),
        migrations.RemoveField(
            model_name="documents",
            name="file_name",
        ),
        migrations.RemoveField(
            model_name="documents",
            name="file_name_en",
        ),
        migrations.RemoveField(
            model_name="documents",
            name="file_name_ru",
        ),
        migrations.RemoveField(
            model_name="documents",
            name="file_name_uz",
        ),
        migrations.RemoveField(
            model_name="regulations",
            name="file_name",
        ),
        migrations.RemoveField(
            model_name="regulations",
            name="file_name_en",
        ),
        migrations.RemoveField(
            model_name="regulations",
            name="file_name_ru",
        ),
        migrations.RemoveField(
            model_name="regulations",
            name="file_name_uz",
        ),
        migrations.AlterField(
            model_name="documents",
            name="title",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="title_en",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="title_ru",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="title_uz",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="regulations",
            name="title",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="regulations",
            name="title_en",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="regulations",
            name="title_ru",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="regulations",
            name="title_uz",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
