# Generated by Django 5.0.6 on 2024-05-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_rename_pdf_documents_document_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
            ],
            options={
                "verbose_name": "Competition Documents",
                "verbose_name_plural": "Competition Documents",
            },
        ),
        migrations.CreateModel(
            name="CompetitionReports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
            ],
            options={
                "verbose_name": "Competition Reports",
                "verbose_name_plural": "Competition Reports",
            },
        ),
    ]
