# Generated by Django 5.0.6 on 2024-06-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_eventsaboutus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventsaboutus",
            name="link_en",
        ),
        migrations.RemoveField(
            model_name="eventsaboutus",
            name="link_ru",
        ),
        migrations.RemoveField(
            model_name="eventsaboutus",
            name="link_uz",
        ),
    ]
