# Generated by Django 5.0.6 on 2024-05-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_competitiondocuments_competitionreports"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitiondocuments",
            name="document_en",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="competitiondocuments",
            name="document_ru",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="competitiondocuments",
            name="document_uz",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="competitiondocuments",
            name="title_en",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="competitiondocuments",
            name="title_ru",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="competitiondocuments",
            name="title_uz",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="competitionreports",
            name="document_en",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="competitionreports",
            name="document_ru",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="competitionreports",
            name="document_uz",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="competitionreports",
            name="title_en",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="competitionreports",
            name="title_ru",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="competitionreports",
            name="title_uz",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
