# Generated by Django 5.0.6 on 2024-05-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_competitiondocuments_document_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="carousel/")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
