# Generated by Django 5.0.6 on 2024-06-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_remove_eventsaboutus_link_en_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventsaboutus",
            old_name="link",
            new_name="url",
        ),
    ]
