# Generated by Django 5.0.6 on 2024-06-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_rename_link_eventsaboutus_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.CharField(max_length=256)),
            ],
            options={
                "verbose_name": "Галерея Видео",
                "verbose_name_plural": "Галерея Видео",
            },
        ),
    ]
