# Generated by Django 5.0.6 on 2024-06-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_galleryvideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsaboutus",
            name="title",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
