# Generated by Django 5.0.6 on 2024-05-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_aboutconfederation_content_en_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutconfederation",
            options={
                "verbose_name": "Confederation",
                "verbose_name_plural": "Confederation",
            },
        ),
        migrations.AddField(
            model_name="aboutconfederation",
            name="title",
            field=models.CharField(default="data", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aboutconfederation",
            name="title_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="aboutconfederation",
            name="title_ru",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="aboutconfederation",
            name="title_uz",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
