# Generated by Django 5.0.6 on 2024-05-24 20:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0004_alter_aboutconfederation_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutGuides",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                "verbose_name": "Guides",
                "verbose_name_plural": "Guides",
            },
        ),
        migrations.CreateModel(
            name="AboutMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Membership",
            },
        ),
    ]
