# Generated by Django 5.0.6 on 2024-05-24 20:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0005_aboutguides_aboutmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutguides",
            name="content_en",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name="aboutguides",
            name="content_ru",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name="aboutguides",
            name="content_uz",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name="aboutguides",
            name="title_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="aboutguides",
            name="title_ru",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="aboutguides",
            name="title_uz",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="aboutmembership",
            name="content_en",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name="aboutmembership",
            name="content_ru",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name="aboutmembership",
            name="content_uz",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name="aboutmembership",
            name="title_en",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="aboutmembership",
            name="title_ru",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="aboutmembership",
            name="title_uz",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
