# Generated by Django 5.0.6 on 2024-05-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0007_aboutsymbols"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("pdf", models.FileField(upload_to="documents/")),
            ],
            options={
                "verbose_name": "Documents",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.CreateModel(
            name="AboutRegulations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("pdf", models.FileField(upload_to="documents/")),
            ],
            options={
                "verbose_name": "Regulations",
                "verbose_name_plural": "Regulations",
            },
        ),
    ]
