# Generated by Django 5.0.6 on 2024-05-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0009_aboutdocuments_title_en_aboutdocuments_title_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutdocuments",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="aboutregulations",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
    ]
