# Generated by Django 5.0.6 on 2024-05-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0011_aboutdocuments_pdf_en_aboutdocuments_pdf_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutdocuments",
            name="file_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="aboutregulations",
            name="file_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
