# Generated by Django 5.0.6 on 2024-05-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0012_aboutdocuments_file_name_aboutregulations_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutdocuments",
            name="file_name_en",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="aboutdocuments",
            name="file_name_ru",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="aboutdocuments",
            name="file_name_uz",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="aboutregulations",
            name="file_name_en",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="aboutregulations",
            name="file_name_ru",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="aboutregulations",
            name="file_name_uz",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
